# Generated by Django 4.1.5 on 2023-02-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_working_location_usable'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='nearby',
            field=models.BooleanField(default=False),
        ),
    ]
