# Generated by Django 4.1.5 on 2023-03-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_challenges_userdata_delete_pointssystem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenges',
            new_name='Challenge',
        ),
    ]
