# Generated by Django 4.1.5 on 2023-03-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_challenges_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='challenge_ID',
            new_name='current_challenge',
        ),
    ]
