# Generated by Django 4.1.5 on 2023-03-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userprofile_delete_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='score',
            new_name='points_lifetime',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points_this_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points_wallet',
            field=models.IntegerField(default=0),
        ),
    ]
