# Generated by Django 4.1.5 on 2023-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_challenge_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fountains_used', models.IntegerField(default=0)),
                ('bus_stops_used', models.IntegerField(default=0)),
                ('bins_used', models.IntegerField(default=0)),
                ('total_used', models.IntegerField(default=0)),
            ],
        ),
    ]
