# Generated by Django 4.1.5 on 2023-02-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_items_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('Fountain', 'Fountain'), ('BusStop', 'BusStop'), ('Bin', 'Bin')], default='Fountain', max_length=8),
        ),
    ]
