# Generated by Django 4.1.5 on 2023-02-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_location_report_location_working'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='working',
            new_name='usable',
        ),
    ]
