# Generated by Django 4.1.5 on 2023-02-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_location_location_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='report',
        ),
        migrations.AddField(
            model_name='location',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
