name: HTML Linter (djlint)

on:
  push:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        pip install djlint
    - name: Analyse HTML with djlint
      run: | 
        djlint /path/to/templates --profile=django
        djlint . --extension=html.j2 --lint
        djlint . --extension=html.j2 --check
